version: 1.0
album:
    - name: House
      friendly_name: 房间
      preview: _DSC2670 - 01.jpg
    - name: Polaroid
      friendly_name: Polaroid
      preview: IMG_0546.jpg
    - name: Shot on Film
      friendly_name: 胶片
      preview: RVP1001.jpg
